# Generated by Django 5.0.1 on 2025-11-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='workflow_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
